name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.CREDS_GCP }}

      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: finanzas-personales-deploy
          description: Test python cloud function
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: us-east4
          source_dir: .
          entry_point: handle_gcs_event
          runtime: python310
          timeout: 60
          max_instances: 1
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: projects/_/buckets/finanzas_personales_raw
          event_trigger_retry: false
          deploy_timeout: 300
